string frame
float64 x 0.
float64 y 0.
float64 covariance_factor 0.01          # published covariance factor (covariance = factor * range)
float64 covariance_factor_real 0.01     # simulated covariance (real covariance = real factor * range)
float64 range_min 0.
float64 range_max 100.
---
